name: Apply terraform plan

env:
  AWS_REGION: us-east-1

on:
  push:
    branches: [main]

jobs:
  ci-cd:
    name: terraform-apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize terraform
        id: init
        run: terraform init
        continue-on-error: true

      - name: Format terraform
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Plan terraform
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: Apply terraform
        id: apply
        run: terraform apply -auto-approve -input=false
        continue-on-error: true

        env:
          PACKET_LOG: 1